version: '3.7'

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    env_file:
      - .env
  blog-backend:
    image: spring-boot:latest
    container_name: blog-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    expose:
      - "8000"
    volumes:
      - ./uploads:/app/uploads
  nginx:
    container_name: nginx
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/app/uploads
    depends_on:
      - blog-backend
    restart: always